# Generated by Django 3.1.4 on 2021-01-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
    ]
